### ISSUE TITLE
Download fails if Database folder exists

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#39]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/4cf85e64-66f0-459f-9215-f306b914e98f)

We have to check if the dir already exists.

**Comment by Porthmeus** [comment]
We should rewrite the code anyway to integrate the download of the different databases in a more flexible way. See #38. I would suggest taking the part where the generic download call is defined to a dedicated function and calling the different functions for the different databases within the `database_db.py` individually.

**Comment by Unaimend** [comment]
yes. I have the same solution in mind

**Comment by Porthmeus** [comment]
I have a written an update function which can be called ... it checks only if the database already exists, if yes, it will delete it and download it again. This circumvents the problem of the database directory. And since the databases are clearly defined in the config.yml, there is little chance to overwrite user files.
